services:
  - type: web
    name: faysal-site
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/omarfaysal1111/faysal-site
    branch: main
    region: frankfurt
    plan: starter
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: CONTACT_TO_EMAIL
        value: info@faysalstudio.com
      - key: CONTACT_FROM_EMAIL
        value: FAYSAL Studio <info@faysalstudio.com>
